### ISSUE TITLE
Bug in CompositeLJ energy evaluation

### ISSUE THREAD

**Issue by junchichen21** [wexlergroup/FreeBird.jl#52]
https://github.com/wexlergroup/FreeBird.jl/blob/ba083f0dbbf40ad3a904d5c612b2bab33e602598/src/EnergyEval/EnergyEval.jl#L138

The original code only considers the upper triangle of the LJ interaction matrix. When asymmetric LJ interactions are given (i.e., 13 != 31), this will give incorrect energy.

**Comment by yangmr04** [comment]
Good catch! Will fix soon! As we so far never used asymmetric LJ, no previous calculation results were impacted.

**Comment by yangmr04** [comment]
Fixed by PR #54. Closed.
